name: sample html export

on:
  push:
    branch:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install netlify CLI
        run: npm install -g netlify-cli
        
      - name: deploy to netlify
        run: |
          netlify deploy --prod \
            --dir=. \
            --site ${{ secrets.NETLIFY_SITE_ID}} \
            --auth ${{ secrets.NETLIFY_API_TOKEN}}